server:
  port: ${APP_SERVER_PORT:8080}
  servlet:
    context-path: /api/v1

spring:
  application:
    name: kotlin-spring-cloud-stream
  profiles:
    active: ${APP_PROFILE:dev}
    include:
      - kafka
#  security:
#    oauth2:
#      resourceserver:
#        jwt:
#          issuer-uri: ${APP_OAUTH_SERVER:https://dev.jandrinet.com/auth/realms/jandrinet}
#          jwk-set-uri: ${APP_OAUTH_SERVER_CERTS:https://dev.jandrinet.com/auth/realms/jandrinet/protocol/openid-connect/certs}
  jackson:
    property-naming-strategy: SNAKE_CASE
    default-property-inclusion: non_null
  # DATABASE
  jpa:
    properties:
      hibernate:
        default_schema: ${APP_POSTGRES_SCHEMA:public}
    database: POSTGRESQL
    show-sql: true
  datasource:
    url: jdbc:postgresql://${APP_POSTGRES_HOST:localhost}:${APP_POSTGRES_PORT:5432}/${APP_POSTGRES_DB:claimDB}
    username: ${APP_POSTGRES_USER:user}
    password: ${APP_POSTGRES_PASSWORD:password}
    driverClassName: org.postgresql.Driver
  liquibase:
    enabled: true
    change-log: classpath:/db/changelog-master.xml
    default-schema: ${APP_POSTGRES_SCHEMA:public}
    contexts: ${spring.profiles.active}
  h2.console.enabled: true

app:
  security:
    jwtSigningSecret: JWTSuperSecretKey
    jwtExpirationInMs: 604800000


# ACTUATOR ENDPOINTS
management:
  security:
    enabled: false
  context-path: /actuator
  endpoint:
    health:
      show-details: always
      show-components: always
    web:
      base-path: /actuator
      exposure:
        include: actuator, health, info, prometheus
  health:
    probes:
      enabled: true

# OPENAPI GENERATION
springdoc:
  api-docs:
    path: api-docs
  swagger-ui:
    path: /swagger-ui.html

openapi-server-url: ${APP_GATEWAY_URL:http://localhost:8003/comms-attachments/api}

# LOGGING
logging:
  config: classpath:logback-spring.xml
  level:
    org.zalando.logbook: TRACE
    liquibase: INFO

logbook:
  format.style: json
  exclude:
    - /**/actuator/health
    - /**/swagger-ui.html
    - /**/swagger-ui/**
  obfuscate:
    headers:
      - Authorization
      - X-Secret
    parameters:
      - access_token
      - password
      - first_name
      - last_name
      - birth_date
      - credit_card
      - cvc
    body:
      - document
  write:
    chunk-size: 1000
