FROM adoptopenjdk/openjdk11:jdk-11.0.10_9-slim

ARG USERNAME
ARG PASSWORD

COPY wait-for-it.sh wait-for-it.sh
COPY wait-for-it.sh /wait-for-it.sh

RUN chmod +x wait-for-it.sh
RUN chmod +x /wait-for-it.sh

