#ARG ELK_VERSION

# https://github.com/elastic/elasticsearch-docker
FROM obsidiandynamics/kafdrop:3.28.0-SNAPSHOT

COPY --chown=1000:1000 wait-for-it.sh wait-for-it.sh
COPY --chown=1000:1000 wait-for-it.sh /wait-for-it.sh

RUN chmod +x wait-for-it.sh
RUN chmod +x /wait-for-it.sh