spring:
  # kafka
  cloud:
    stream:
      default-binder: kafka
      function:
        definition: "producer"
      bindings:
        # consumer
        producer-out-0:
          destination: ${APP_TOPIC_EXECUTE_CREATE_ATTACHMENTS_COMMAND:command.comms.create-documents}
          group: ${APP_TOPIC_EXECUTE_CREATE_ATTACHMENTS_GROUP:group.comms.documents}

      kafka:
        bindings:
          producer-out-0:
            producer:
              topic.properties:
                message.format.version: 1.0.0

        binder:
          brokers: ${APP_KAFKA_BROKERS:localhost:29092}
          replication-factor: ${APP_KAFKA_REPLICATION_FACTOR:1}
          auto-create-topics: true
          auto-add-partitions: true
#          required-acks: all
          configuration:
            security.protocol: ${APP_KAFKA_SECURITY_PROTOCOL:PLAINTEXT}
            ssl.truststore.location: ${APP_KAFKA_TRUSTSTORE:}
#            auto.offset.reset: earliest

