#FROM adoptopenjdk/openjdk11:jdk-11.0.10_9-slim as compiler
FROM gradle:jdk11-openj9 as compiler
LABEL stage=compiler
WORKDIR workdir

CMD pwd

COPY . .
COPY docker/wait-for-it.sh .
COPY docker/start.sh .

ARG USERNAME
ARG PASSWORD
#RUN ./gradlew assemble  || return 0
RUN gradle assemble  || return 0

# build
FROM adoptopenjdk:11-jre-hotspot as builder
LABEL stage=builder
WORKDIR application

COPY --from=compiler workdir/application/build/libs/application-1.0.0.jar ./application.jar
COPY --from=compiler workdir/wait-for-it.sh ./
COPY --from=compiler workdir/start.sh ./
RUN java -Djarmode=layertools -jar application.jar extract

# image
FROM adoptopenjdk:11-jre-hotspot
WORKDIR application
COPY --from=builder application.jar ./
COPY --from=builder application/wait-for-it.sh ./
COPY --from=builder application/start.sh ./
RUN chmod +x wait-for-it.sh
RUN chmod +x start.sh

#COPY --from=builder application/dependencies/ ./
#COPY --from=builder application/spring-boot-loader/ ./
#COPY --from=builder application/snapshot-dependencies/ ./
#COPY --from=builder application/application/ ./

RUN cp /opt/java/openjdk/lib/security/cacerts /application/kafka.client.truststore.jks

VOLUME /tmp
EXPOSE 8080
#ENTRYPOINT ["java","-Xms256m","-Xmx512m", "org.springframework.boot.loader.JarLauncher"]
ENTRYPOINT ["java","-Xms256m","-Xmx512m", "application.jar"]